name: ${name}
version: ${version}
main: ${group}.${name}
description: ${description}
api-version: 1.18
authors: [ YouHaveTrouble, CorvetteCole, Dashiell ]
website: youhavetrouble.me
softdepend:
  - PlaceholderAPI
  - Vault
permissions:
  serverbasics.command.fly.*:
    children:
      serverbasics.command.fly: true
      serverbasics.command.fly.others: true
  serverbasics.command.fix.*:
    default: op
    children:
      serverbasics.command.fix.hand: true
      serverbasics.command.fix.all: true
  serverbasics.command.fix.hand:
    children:
      serverbasics.command.fix: true
  serverbasics.command.fix.all:
    children:
      serverbasics.command.fix: true
  serverbasics.command.gamemode.*:
    default: op
    children:
      serverbasics.command.gamemode.self.*: true
      serverbasics.command.gamemode.others.*: true
  serverbasics.command.gamemode.self.*:
    children:
      serverbasics.command.gamemode: true
      serverbasics.command.gamemode.self.survival: true
      serverbasics.command.gamemode.self.creative: true
      serverbasics.command.gamemode.self.adventure: true
      serverbasics.command.gamemode.self.spectator: true
  serverbasics.command.gamemode.others.*:
    children:
      serverbasics.command.gamemode: true
      serverbasics.command.gamemode.others.survival: true
      serverbasics.command.gamemode.others.creative: true
      serverbasics.command.gamemode.others.adventure: true
      serverbasics.command.gamemode.others.spectator: true
  serverbasics.chat.color:
    description: Allows usage of colors in chat
    default: op
  serverbasics.chat.staffchat.*:
    default: op
    children:
      serverbasics.chat.staffchat.send: true
      serverbasics.chat.staffchat.recieve: true
  serverbasics.hat.equip:
    description: Allows equipping hat in the survival inventory
    default: op
  serverbasics.command.nick.change:
    description: Allows player to change their own nickname and not only change colors
  serverbasics.command.enchant.unsafe:
    default: op
    children:
      serverbasics.command.enchant: true
    description: Allows applying unsafe enchantments with /enchant command
  serverbasics.command.execute.bypass:
    default: op
    description: Users with this permission cannot have execute command used on them
