name: ServerBasics
version: ${project.version}
main: eu.endermite.serverbasics.ServerBasics
api-version: 1.13
authors: [ YouHaveTrouble, CorvetteCole, Dashiell ]
softdepend:
  - PlaceholderAPI
permissions:
  serverbasics.gamemode:
    default: op
    children:
      serverbasics.gamemode.self:
        serverbasics.gamemode.self.survival:
          description: Allows switching to survival mode
        serverbasics.gamemode.self.creative:
          description: Allows switching to creative mode
        serverbasics.gamemode.self.adventure:
          description: Allows switching to adventure mode
        serverbasics.gamemode.self.spectator:
          description: Allows switching to spectator mode
      serverbasics.gamemode.others:
        children:
          serverbasics.gamemode.others.survival:
            description: Allows switching other players to survival mode
          serverbasics.gamemode.others.creative:
            description: Allows switching other players to creative mode
          serverbasics.gamemode.others.adventure:
            description: Allows switching other players to adventure mode
          serverbasics.gamemode.others.spectator:
            description: Allows switching other players to spectator mode
  serverbasics.chat.color:
    description: Allows usage of colors in chat
    default: op
  serverbasics.chat.staffchat:
    default: op
    children:
      serverbasics.chat.staffchat.send:
        description: Allows sending messages in staff chat
      serverbasics.chat.staffchat.recieve:
        description: Allows recieving messages from staffchat
  serverbasics.command.hat.equip:
    description: Allows equipping hat in the survival inventory
    default: op
  serverbasics.command.nick.change:
    description: Allows player to change their own nickname and not only change colors
