name: ServerBasics
version: ${project.version}
main: eu.endermite.serverbasics.ServerBasics
api-version: 1.13
authors: [ YouHaveTrouble, CorvetteCole, Dashiell ]
softdepend:
  - PlaceholderAPI
permissions:
  serverbasics.gamemode.self.survival:
    description: Allows switching to survival mode
    default: op
  serverbasics.gamemode.self.creative:
    description: Allows switching to creative mode
    default: op
  serverbasics.gamemode.self.adventure:
    description: Allows switching to adventure mode
    default: op
  serverbasics.gamemode.self.spectator:
    description: Allows switching to spectator mode
    default: op
  serverbasics.gamemode.others.survival:
    description: Allows switching other players to survival mode
    default: op
  serverbasics.gamemode.others.creative:
      description: Allows switching other players to creative mode
      default: op
  serverbasics.gamemode.others.adventure:
      description: Allows switching other players to adventure mode
      default: op
  serverbasics.gamemode.others.spectator:
      description: Allows switching other players to spectator mode
      default: op
  serverbasics.chat.color:
    description: Allows usage of colors in chat
    default: op
  serverbasics.command.hat.equip:
    description: Allows equipping hat in the survival inventory
    default: op
