name: ServerBasics
version: ${project.version}
main: eu.endermite.serverbasics.ServerBasics
api-version: 1.17
authors: [ YouHaveTrouble, CorvetteCole, Dashiell ]
softdepend:
  - PlaceholderAPI
  - Vault
permissions:
  serverbasics.command.fly.*:
    children:
      serverbasics.command.fly: true
      serverbasics.command.fly.others: true
  serverbasics.command.fix.*:
    default: op
    children:
      serverbasics.command.fix.hand: true
      serverbasics.command.fix.all: true
  serverbasics.command.fix.hand:
    children:
      serverbasics.command.fix: true
  serverbasics.command.fix.all:
    children:
      serverbasics.command.fix: true
  serverbasics.command.gamemode.*:
    default: op
    children:
      serverbasics.command.gamemode.self.*: true
      serverbasics.command.gamemode.others.*: true
  serverbasics.command.gamemode.self.*:
    children:
      serverbasics.command.gamemode: true
      serverbasics.command.gamemode.self.survival: true
      serverbasics.command.gamemode.self.creative: true
      serverbasics.command.gamemode.self.adventure: true
      serverbasics.command.gamemode.self.spectator: true
  serverbasics.command.gamemode.others.*:
    children:
      serverbasics.command.gamemode: true
      serverbasics.command.gamemode.others.survival: true
      serverbasics.command.gamemode.others.creative: true
      serverbasics.command.gamemode.others.adventure: true
      serverbasics.command.gamemode.others.spectator: true
  serverbasics.chat.color:
    description: Allows usage of colors in chat
    default: op
  serverbasics.chat.staffchat.*:
    default: op
    children:
      serverbasics.chat.staffchat.send: true
      serverbasics.chat.staffchat.recieve: true
  serverbasics.hat.equip:
    description: Allows equipping hat in the survival inventory
    default: op
  serverbasics.command.nick.change:
    description: Allows player to change their own nickname and not only change colors
